version: "3.8"

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file: .env.local
    ports:
      - "3000:3000"
